In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import git

In [27]:
repo_path = git.Repo('.', search_parent_directories=True).working_tree_dir
data_path = repo_path + '/data/raw/'

In [28]:
# load disney plus data
df_disney = pd.read_csv(data_path + 'disney_plus_shows.csv')

df_disney.head(2)

,imdb_id,title,plot,type,rated,year,released_at,added_at,runtime,genre,director,writer,actors,language,country,awards,metascore,imdb_rating,imdb_votes
0,tt0147800,10 Things I Hate About You,"A pretty, popular teenager can't go out on a d...",movie,PG-13,1999,31 Mar 1999,"November 12, 2019",97 min,"Comedy, Drama, Romance",Gil Junger,"Karen McCullah, Kirsten Smith","Heath Ledger, Julia Stiles, Joseph Gordon-Levi...","English, French",USA,2 wins & 13 nominations.,70.0,7.3,"283,945"
1,tt7019028,101 Dalmatian Street,This series follows the lives of Delilah and D...,series,NaN,2018–,25 Mar 2019,"February 28, 2020",NaN,"Animation, Comedy, Family",NaN,NaN,"Josh Brener, Michaela Dietz, Bert Davis, Abiga...",English,"UK, USA, Canada",NaN,NaN,6.2,124

In [29]:
df_disney.head(2)

,imdb_id,title,plot,type,rated,year,released_at,added_at,runtime,genre,director,writer,actors,language,country,awards,metascore,imdb_rating,imdb_votes
0,tt0147800,10 Things I Hate About You,"A pretty, popular teenager can't go out on a d...",movie,PG-13,1999,31 Mar 1999,"November 12, 2019",97 min,"Comedy, Drama, Romance",Gil Junger,"Karen McCullah, Kirsten Smith","Heath Ledger, Julia Stiles, Joseph Gordon-Levi...","English, French",USA,2 wins & 13 nominations.,70.0,7.3,"283,945"
1,tt7019028,101 Dalmatian Street,This series follows the lives of Delilah and D...,series,NaN,2018–,25 Mar 2019,"February 28, 2020",NaN,"Animation, Comedy, Family",NaN,NaN,"Josh Brener, Michaela Dietz, Bert Davis, Abiga...",English,"UK, USA, Canada",NaN,NaN,6.2,124

In [31]:
df_disney.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 992 entries, 0 to 991
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   imdb_id      894 non-null    object
 1   title        894 non-null    object
 2   plot         866 non-null    object
 3   type         894 non-null    object
 4   rated        742 non-null    object
 5   year         894 non-null    object
 6   released_at  874 non-null    object
 7   added_at     992 non-null    object
 8   runtime      838 non-null    object
 9   genre        885 non-null    object
 10  director     689 non-null    object
 11  writer       743 non-null    object
 12  actors       870 non-null    object
 13  language     856 non-null    object
 14  country      869 non-null    object
 15  awards       556 non-null    object
 16  metascore    292 non-null    float64
 17  imdb_rating  879 non-null    float64
 18  imdb_votes   879 non-null    object
dtypes: float64(2), object(17)
memory usage: 147.4+ KB

In [25]:
# drop if imdb_id and title is null
df_disney = df_disney.dropna(subset=['imdb_id', 'title'])

In [35]:
df_disney['year'].unique()[100:150]

array(['1936', '1964', '1975', '2000–2003', '1994–1996', '2006–2010',
       '2010–2014', '1984', '1976', '2014–2017', '1992–1993', '1934',
       '2006–2013', '2006–2011', '2013–', '1980', '1974', '1944',
       '2013–2015', '2008–', '2008–2012', '2011–2015', '1960', '1972',
       '1952', '2003–2006', '2001–2004', '1994–1998', '1996–1998',
       '1992–1997', '2012–2017', '1948', '1955–1958', '1983', '1969',
       '2007–2010', '1957', '1935', '1985', '1998–2004', '2004–2006',
       '2007–2015', '1978', '1973', '2010–2013', '1997–1999', '1999–2001',
       '2009–2011', '1981–1982', '1981–1986'], dtype=object)

In [22]:
df_disney.head(2)

,imdb_id,title,plot,type,rated,year,released_at,added_at,runtime,genre,director,writer,actors,language,country,awards,metascore,imdb_rating,imdb_votes,imdb_link
0,"<a href=""https://www.imdb.com/title/tttt014780...",10 things i hate about you,"A pretty, popular teenager can't go out on a d...",movie,PG-13,1999,31 Mar 1999,"November 12, 2019",97 min,"Comedy, Drama, Romance",Gil Junger,"Karen McCullah, Kirsten Smith","Heath Ledger, Julia Stiles, Joseph Gordon-Levi...","English, French",USA,2 wins & 13 nominations.,70.0,7.3,"283,945","<a href=""https://www.imdb.com/title/tt0147800""..."
1,"<a href=""https://www.imdb.com/title/tttt701902...",101 dalmatian street,This series follows the lives of Delilah and D...,series,NaN,2018–,25 Mar 2019,"February 28, 2020",NaN,"Animation, Comedy, Family",NaN,NaN,"Josh Brener, Michaela Dietz, Bert Davis, Abiga...",English,"UK, USA, Canada",NaN,NaN,6.2,124,"<a href=""https://www.imdb.com/title/tt7019028""..."

In [19]:
# load IMDB movies data
df_imdb_movies = pd.read_csv(data_path + 'IMDb_movies.csv', low_memory=False)  

df_imdb_movies.head(2)

,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,director,...,actors,description,avg_vote,votes,budget,usa_gross_income,worlwide_gross_income,metascore,reviews_from_users,reviews_from_critics
0,tt0000009,Miss Jerry,Miss Jerry,1894,1894-10-09,Romance,45,USA,NaN,Alexander Black,...,"Blanche Bayliss, William Courtenay, Chauncey D...",The adventures of a female reporter in the 1890s.,5.9,154,NaN,NaN,NaN,NaN,1.0,2.0
1,tt0000574,The Story of the Kelly Gang,The Story of the Kelly Gang,1906,1906-12-26,"Biography, Crime, Drama",70,Australia,NaN,Charles Tait,...,"Elizabeth Tait, John Tait, Norman Campbell, Be...",True story of notorious Australian outlaw Ned ...,6.1,589,$ 2250,NaN,NaN,NaN,7.0,7.0

In [20]:
# extract the title from disney data and find the corresponding movie in IMDB data
df_disney['title'] = df_disney['title'].str.lower()

df_imdb_movies['title'] = df_imdb_movies['title'].str.lower()

In [10]:
# now use fuzzy matching to find the closest match
from thefuzz import fuzz
from thefuzz import process

In [36]:
# compare the imdb title with disney title and then add the imdb rows to disney data, using fuzzy matching
def get_imdb_data(row):
    title = row['title']
    year = row['year']
    ratio = 0
    match = ''
    for i in range(0, len(df_imdb_movies)):
        if df_imdb_movies.iloc[i]['year'] == year:
            if fuzz.ratio(title, df_imdb_movies.iloc[i]['title']) > ratio:
                ratio = fuzz.ratio(title, df_imdb_movies.iloc[i]['title'])
                match = i
    if ratio > 70:
        return df_imdb_movies.iloc[match]
    else:
        return None

In [37]:
# get the imdb data for disney movies
df_disney['imdb_data'] = df_disney.apply(get_imdb_data, axis=1)

In [39]:
df_disney.head(20)

,imdb_id,title,plot,type,rated,year,released_at,added_at,runtime,genre,director,writer,actors,language,country,awards,metascore,imdb_rating,imdb_votes,imdb_data
0,tt0147800,10 Things I Hate About You,"A pretty, popular teenager can't go out on a d...",movie,PG-13,1999,31 Mar 1999,"November 12, 2019",97 min,"Comedy, Drama, Romance",Gil Junger,"Karen McCullah, Kirsten Smith","Heath Ledger, Julia Stiles, Joseph Gordon-Levi...","English, French",USA,2 wins & 13 nominations.,70.0,7.3,"283,945",None
1,tt7019028,101 Dalmatian Street,This series follows the lives of Delilah and D...,series,NaN,2018–,25 Mar 2019,"February 28, 2020",NaN,"Animation, Comedy, Family",NaN,NaN,"Josh Brener, Michaela Dietz, Bert Davis, Abiga...",English,"UK, USA, Canada",NaN,NaN,6.2,124,None
2,tt0115433,101 Dalmatians,An evil high-fashion designer plots to steal D...,movie,G,1996,27 Nov 1996,"November 12, 2019",103 min,"Adventure, Comedy, Crime, Family",Stephen Herek,"Dodie Smith (novel), John Hughes (screenplay)","Glenn Close, Jeff Daniels, Joely Richardson, J...","English, Spanish","USA, UK",Nominated for 1 Golden Globe. Another 3 wins &...,49.0,5.7,"97,785",None
3,tt0324941,101 Dalmatians 2: Patch's London Adventure,"Being one of 101 takes its toll on Patch, who ...",movie,G,2002,21 Jan 2003,"November 12, 2019",74 min,"Animation, Adventure, Comedy, Family, Musical","Jim Kammerud, Brian Smith","Jim Kammerud (story), Dan Root (story), Garret...","Barry Bostwick, Jason Alexander, Martin Short,...",English,USA,5 wins & 10 nominations.,NaN,5.8,"7,434",None
4,tt0211181,102 Dalmatians,Cruella DeVil gets out of prison and goes afte...,movie,G,2000,22 Nov 2000,"November 12, 2019",100 min,"Adventure, Comedy, Family",Kevin Lima,"Dodie Smith (novel), Kristen Buckley (story), ...","Glenn Close, Gérard Depardieu, Ioan Gruffudd, ...",English,"USA, UK",Nominated for 1 Oscar. Another 1 win & 7 nomin...,35.0,4.9,"33,444",None
5,tt1846442,12 Dates of Christmas,"A story that follows Kate, a young woman who a...",movie,PG,2011,11 Dec 2011,"November 12, 2019",90 min,"Comedy, Fantasy, Romance",James Hayman,"Aaron Mendelsohn (teleplay), Janet Brownell (t...","Laura Miyata, Vijay Mehta, Amy Smart, Audrey D...",English,USA,1 nomination.,NaN,6.3,"4,933",None
6,tt0046672,"20,000 Leagues Under the Sea",A ship sent to investigate a wave of mysteriou...,movie,G,1954,20 Jul 1955,"November 12, 2019",127 min,"Adventure, Drama, Family, Fantasy, Sci-Fi",Richard Fleischer,Earl Felton (screenplay),"Kirk Douglas, James Mason, Paul Lukas, Peter L...",English,USA,Won 2 Oscars. Another 3 wins & 3 nominations.,83.0,7.2,"27,761",None
7,tt0120623,A Bug's Life,"A misfit ant, looking for ""warriors"" to save h...",movie,G,1998,25 Nov 1998,"November 12, 2019",95 min,"Animation, Adventure, Comedy, Family","John Lasseter, Andrew Stanton(co-director)","John Lasseter (original story by), Andrew Stan...","Dave Foley, Kevin Spacey, Julia Louis-Dreyfus,...",English,USA,Nominated for 1 Oscar. Another 14 wins & 20 no...,77.0,7.2,"257,065",None
8,tt12076020,A Celebration of the Music from Coco,NaN,movie,NaN,2020,10 Apr 2020,"April 10, 2020",NaN,Music,Ron de Moraes,NaN,"Benjamin Bratt, Eva Longoria",English,USA,NaN,NaN,7.6,35,None
9,tt0113198,A Goofy Movie,When Max makes a preposterous promise to a gir...,movie,G,1995,07 Apr 1995,"November 12, 2019",78 min,"Animation, Adventure, Comedy, Family, Musical,...",Kevin Lima,"Jymn Magon (story), Jymn Magon (screenplay), C...","Bill Farmer, Jason Marsden, Jim Cummings, Kell...",English,"USA, Australia, France, Canada",5 nominations.,NaN,6.8,"43,655",None
10,tt0113538,A Kid in King Arthur's Court,A Little League player is sent back into medie...,movie,PG,1995,11 Aug 1995,"November 12, 2019",89 min,"Adventure, Comedy, Family, Fantasy, Romance",Michael Gottlieb,"Michael Part, Robert L. Levy","Thomas Ian Nicholas, Joss Ackland, Art Malik, ...",English,"USA, Hungary, UK",1 nomination.,34.0,4.7,"5,479",None
11,tt0038674,A Knight for a Day,"By accident, Cedric (Goofy), replaces his mast...",movie,APPROVED,1946,08 Mar 1946,"November 12, 2019",7 min,"Animation, Short, Comedy",Jack Hannah,Bill Peet (story),Pinto Colvig,English,USA,NaN,NaN,7.0,488,None
12,tt0282123,A Ring of Endless Light,Based on the Novel by Madeline L'Engle. During...,movie,TV-G,2002,23 Aug 2002,"November 12, 2019",88 min,"Drama, Family, Romance",Greg Beeman,"Madeleine L'Engle (novel), Marita Giovanni (te...","Mischa Barton, Ryan Merriman, Jared Padalecki,...",English,USA,2 wins & 1 nomination.,NaN,6.1,"1,042",None
13,tt0287003,A Tale of Two Critters,A bear cub and a raccoon become fast friends w...,movie,G,1977,22 Jun 1977,"April 3, 2020",48 min,"Adventure, Family",Jack Speirs,Jack Speirs,Mayf Nutter,English,USA,NaN,NaN,7.1,59,imdb_title_id ...
14,tt1620680,A Wrinkle in Time,After the disappearance of her scientist fathe...,movie,PG,2018,09 Mar 2018,"March 25, 2020",109 min,"Adventure, Family, Fantasy, Sci-Fi",Ava DuVernay,"Jennifer Lee (screenplay by), Jeff Stockwell (...","Storm Reid, Oprah Winfrey, Reese Witherspoon, ...",English,USA,5 wins & 15 nominations.,53.0,4.2,"38,659",imdb_title_id ...
15,tt6139732,Aladdin,A kind-hearted street urchin and a power-hungr...,movie,PG,2019,24 May 2019,"January 8, 2020",128 min,"Adventure, Family, Fantasy, Musical, Romance",Guy Ritchie,"John August (screenplay by), Guy Ritchie (scre...","Will Smith, Mena Massoud, Naomi Scott, Marwan ...","English, Arabic",USA,7 wins & 32 nominations.,53.0,7.0,"204,537",imdb_title_id ...
16,tt0103639,Aladdin,A kindhearted street urchin and a power-hungry...,movie,G,1992,25 Nov 1992,"November 12, 2019",90 min,"Animation, Adventure, Comedy, Family, Fantasy,...","Ron Clements, John Musker","Ron Clements (screenplay by), John Musker (scr...","Scott Weinger, Robin Williams, Linda Larkin, J...",English,USA,Won 2 Oscars. Another 31 wins & 22 nominations.,86.0,8.0,"356,283",imdb_title_id ...
17,tt0115491,Aladdin and the King of Thieves,The King of Thieves disrupts Aladdin and Jasmi...,movie,Not Rated,1996,13 Aug 1996,"November 12, 2019",81 min,"Animation, Adventure, Comedy, Family, Fantasy,...",Tad Stones,"Mark McCorkle (screenplay by), Robert Schooley...","Val Bettin, Jim Cummings, Gilbert Gottfried, L...",English,USA,2 wins & 1 nomination.,NaN,6.4,"31,603",None
18,tt0107952,Aladdin and the Return of Jafar,"Jafar comes for revenge on Aladdin, using a fo...",movie,G,1994,20 May 1994,"November 12, 2019",69 min,"Animation, Adventure, Comedy, Family, Fantasy,...","Toby Shelton, Tad Stones, Alan Zaslove","Duane Capizzi (story), Doug Langdale (story), ...","Jason Alexander, Jonathan Freeman, Jeff Bennet...",English,USA,1 nomination.,NaN,5.9,"25,623",None
19,tt0043274,Alice in Wonderland,Alice stumbles into the world of Wonderland. W...,movie,G,1951,14 Sep 1951,"November 12, 2019",75 min,"Animation, Adventure, Family, Fantasy, Musical","Clyde Geronimi, Wilfred Jackson, Hamilton Luske","Lewis Carroll (adaptation), Winston Hibler (st...","Kathryn Beaumont, Ed Wynn, Richard Haydn, Ster...",English,USA,Nominated for 1 Oscar. Another 1 nomination.,68.0,7.4,"123,377",None

In [ ]:
df_imdb_movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85855 entries, 0 to 85854
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   imdb_title_id          85855 non-null  object
 1   title                  85855 non-null  object
 2   original_title         85855 non-null  object
 3   year                   85855 non-null  object
 4   date_published         85855 non-null  object
 5   genre                  85855 non-null  object
 6   duration               85855 non-null  int64
 7   country                85791 non-null  object
 8   language               84954 non-null  object
 9   director               85768 non-null  object
 10  writer                 84283 non-null  object
 11  production_company     81400 non-null  object
 12  actors                 85786 non-null  object
 13  description            83740 non-null  object
 14  avg_vote               85855 non-null  float64
 15  votes                  85855 non-null  int64
 16  budget                 23710 non-null  object
 17  usa_gross_income       15326 non-null  object
 18  worlwide_gross_income  31016 non-null  object
 19  metascore              13305 non-null  float64
 20  reviews_from_users     78258 non-null  float64
 21  reviews_from_critics   74058 non-null  float64
dtypes: float64(4), int64(2), object(16)
memory usage: 14.4+ MB

In [ ]:
# amazon prime data
amazon_data_path = data_path + 'Amazon_Prime_Video_Movies_and_TV_Shows.csv'
df_amazon = pd.read_csv(amazon_data_path, encoding='ISO-8859-1')

In [ ]:
df_amazon.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12035 entries, 0 to 12034
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Sl.No               12034 non-null  float64
 1   Title               12035 non-null  object
 2   Description         12035 non-null  object
 3   Genres              12035 non-null  object
 4   Cast                10533 non-null  object
 5   Director            9891 non-null   object
 6   Production Country  150 non-null    object
 7   Added On            12035 non-null  object
 8   Year                12034 non-null  float64
 9   Text8               11737 non-null  object
 10  Duration(in Mins)   10136 non-null  object
 11  Season              1900 non-null   object
 12  Rating              937 non-null    object
dtypes: float64(2), object(11)
memory usage: 1.2+ MB

In [ ]:
df_amazon.head(2)

,Sl.No,Title,Description,Genres,Cast,Director,Production Country,Added On,Year,Text8,Duration(in Mins),Season,Rating
0,1.0,An American Ghost Story,Paul Anderson (Stephen Twardokus) and his girl...,Horror,"Stephen Twardokus, Jon Gale, Liesel Kopp, Wend...",Derek Cole,NaN,"June 19, 2022",2012.0,18+,90,NaN,NaN
1,2.0,Back Door to Heaven,"A young kid, who starts out stealing small thi...","Action, Drama","Wallace Ford, Stuart Erwin",William K. Howard,NaN,"June 19, 2022",1939.0,7+,84,NaN,NaN

In [ ]:
# find the year where it's NaN
df_amazon[df_amazon['Year'].isnull()]

,Sl.No,Title,Description,Genres,Cast,Director,Production Country,Added On,Year,Text8,Duration(in Mins),Season,Rating
6189,NaN,Title,Description,Genres,Cast,Director,Production Country,Added On,NaN,Text8,Duration(in Mins),Season,Rating

In [ ]:
# drop where year is NaN
df_amazon = df_amazon.dropna(subset=['Year'])

In [ ]:
# convert year to int
df_amazon['Year'] = df_amazon['Year'].astype(int)

In [ ]:
df_amazon.head(2)

,Sl.No,Title,Description,Genres,Cast,Director,Production Country,Added On,Year,Text8,Duration(in Mins),Season,Rating
0,1.0,An American Ghost Story,Paul Anderson (Stephen Twardokus) and his girl...,Horror,"Stephen Twardokus, Jon Gale, Liesel Kopp, Wend...",Derek Cole,NaN,"June 19, 2022",2012,18+,90,NaN,NaN
1,2.0,Back Door to Heaven,"A young kid, who starts out stealing small thi...","Action, Drama","Wallace Ford, Stuart Erwin",William K. Howard,NaN,"June 19, 2022",1939,7+,84,NaN,NaN

In [ ]:
#